# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 全栈之路
subtitle: 田_田的博客
description: 创新需要在一切发生之前研究结局!
author: 田_田
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://wangzitian0.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repository: git@github.com:wangzitian0/wangzitian0.github.io.git
  branch: master
- type: leancloud_counter_security_sync

search:
  path: search.xml
  field: all


algolia:
  applicationID: '1PWF5BJPP1'
  apiKey: '6a2714c5b665823e7132db2aedb81233'
  indexName: 'wangzitian0.github.io'
  chunkSize: 5000

# Configuration for hexo-image-sizes
image_sizes:
  pattern: !!js/regexp /\.(gif|jpg|jpeg|png)$/i
  profiles:
    body:
      width: 700 // height will adjust to preserve aspect ratio
    thumbnail:
      width: 100 // Image will be cropped to a square
      height: 100
    huge:
      height: 1000
      allowEnlargement: true
  defaultProfile: body

# Settings for  TOC(Table Of Content)
toc:
  maxdepth: 3

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content: true
  content_limit: 300
  content_limit_delim: ' '

leancloud_counter_security:
  enable_sync: true
  app_id: itw5YW53yzX17tr3WAdRd9Dd-gzGzoHsz
  app_key: qLjOt8jjizQl0ys5OSdwf10Y
  server_url: https://itw5yw53.lc-cn-n1-shared.com
  username: wangzitian0 # Will be asked while deploying if is left blank
